// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for security
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
console.log('🔍 DEBUG: Supabase client initialization...');
console.log('🔍 DEBUG: SUPABASE_URL:', SUPABASE_URL ? 'SET' : 'MISSING');
console.log('🔍 DEBUG: SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING');

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing required Supabase environment variables');
  console.error('❌ This will cause authentication to fail');
  throw new Error('Missing required Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 20, // Restore normal real-time events
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'syncchat-web',
    },
  },
});